#!/bin/sh

SRC_PATH=$( dirname -- "$( readlink -f -- "$0"; )"; )
PROJ_TEMP_PATH=$SRC_PATH/templates

trunc_path() {
	echo $( echo $1 | rev | cut -d'/' -f $2 | rev | cat) 
}

display_usage() {
	printf "Usage : %s <template_name | list | help | export | paths | pathto> [param]\n" $( trunc_path $0 -2)
}

if [ $# -ne 1 ] && [ $# -ne 2 ]  
then
	display_usage
	exit 0
fi

COMMAND=$1
PROJ_NAME=$([ "$#" -eq 2 ] && echo $2 || echo $1 )

if [ $COMMAND = "list" ]; then
	printf "Listing Templates...\n"
	for entry in "$PROJ_TEMP_PATH"/*
	do
		echo $( trunc_path "$entry" -2 )
	done
elif [ $COMMAND = "help" ]; then
	printf "dirtempmgr: A simple shell script that helps manage template folders\n"
	printf "Written by uncodem(2022)\n\n"	
	display_usage
elif [ $COMMAND = "export" ]; then
	mkdir $PROJ_TEMP_PATH/$PROJ_NAME
	cp -r ./* $PROJ_TEMP_PATH/$PROJ_NAME
elif [ $COMMAND = "paths"  ]; then
	printf "Using (%s) as base path\n\n" $SRC_PATH
	printf "Using (%s) as template path\n\n" $PROJ_TEMP_PATH
elif [ $COMMAND = "pathto" ]; then
	if [ $COMMAND = $PROJ_NAME ]; then 
		printf "Template name must be provided...\n" >&2
		exit 1
	else
		echo $PROJ_TEMP_PATH/$PROJ_NAME
	fi
else
	if [ -d $PROJ_TEMP_PATH/$COMMAND ]; then
		mkdir -p $PROJ_NAME
		cp -r $PROJ_TEMP_PATH/$COMMAND/* $PROJ_NAME
	else
		printf "Template ' %s ' not found\n" $COMMAND >&2
		exit 1
	fi
fi
